theme = "catppuccin_frappe"

[keys.normal]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_visual_line_up"
";" = "move_char_right"

h = "collapse_selection"
A-h = "flip_selections"

[keys.select]
j = "extend_char_left"
k = "extend_visual_line_down"
l = "extend_visual_line_up"
";" = "extend_char_right"

h = "collapse_selection"
A-h = "flip_selections"
