keys:
  - &aleksbgbg age14sw6wksrc68t0m8ftpzmrc75dwajqyehk4vyr6ck33utr8zepatq9fm2gw
  - &streamfox-s age1g50cpepfyud07ccfqf0qfd34qkxpd0gvsyk6ydkzwdstt54yccgqjvn45z
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *aleksbgbg
      - *streamfox-s
